// Generated by typings
// Source: node-wifi.d.ts
declare module 'node-wifi' {
/** Declaration file generated by dts-gen */

export interface IWifiConnect {
    ssid: string;
    password: string;
}

export function connect(opts: IWifiConnect, cb: any): void;

export function disconnect(cb: any): void;

export function getCurrentConnections(cb: any): void;

export function init(options: any): void;

export function scan(cb: any): void;
}
