// Generated by typings
// Source: typings/os-service.d.ts
declare module 'os-service' {
/** Declaration file generated by dts-gen */

export function add(name: string, options?: any, cb?: any, ...args: any[]): any;

export function remove(name: string, cb?: any): void;

export function run(stopCallback: any): void;

export function stop(rcode: number): void;
}
